In [1]:
from lsr_tensor import *
import torch.nn.functional as f
from datasets import *
from federated_algos import *

In [2]:
# Tests
shape, ranks, separation_rank = (64, 64), (8, 8), 2
x_stdev = 1
y_stdev = 0.05
sample_size = 2000
val_sample_size = int(sample_size * 0.1)

with torch.no_grad():
    true_lsr = LSR_tensor(shape, ranks, separation_rank)
    f.normalize(true_lsr.core_tensor, p=2, dim=0, out=true_lsr.core_tensor)
    true_lsr.core_tensor *= (5 / torch.sqrt(torch.sqrt(torch.prod(torch.tensor(ranks)))))
    
    dataset = synthesize_data(true_lsr, sample_size, shape, x_stdev, y_stdev)
    val_dataset = synthesize_data(true_lsr, val_sample_size, shape, x_stdev, y_stdev)

In [3]:
client_datasets = federate_tensor_data(dataset, 5)

In [4]:
hypers = {"max_rounds": 20, "max_iter": 1, "batch_size": None, "lr": 0.01, "momentum": 0.9, "steps": 5}
loss_fn = f.mse_loss
aggregator_fn = avg_aggregation
BCD_federated_full_iteration(shape, ranks, separation_rank, client_datasets, val_dataset, hypers, loss_fn, aggregator_fn, verbose=True)

Parameter containing:
tensor([[ 0.5256, -0.2519,  0.5247, -0.2102,  0.3937,  0.2945,  0.3295, -0.0186],
        [ 0.4040, -0.1638,  1.1829, -1.0325, -0.6408,  0.0917, -0.6185,  0.0488],
        [-0.0163, -0.7249, -0.5875, -0.2041,  1.1188, -0.1450, -0.8370,  0.4612],
        [-0.1537,  0.0870, -0.1831, -0.2306,  0.8248, -0.6985,  0.1886,  0.2251],
        [ 0.2823, -0.2935,  0.8143,  0.1889,  0.6680, -0.7997,  0.1502,  0.1916],
        [ 0.8346,  0.4212,  0.2960, -0.3884,  0.1295, -0.3018, -0.4408, -0.3743],
        [ 0.3052,  0.2727,  0.0667, -0.1365,  0.4646, -0.6588,  0.3375,  0.3722],
        [-0.1658, -0.3803,  0.1688, -0.0200,  1.1673,  0.1515,  0.4591,  1.4081]],
       requires_grad=True)
Parameter containing:
tensor([[ 0.2773, -0.2799,  0.4265,  0.0139,  0.5735, -0.0072,  0.5603,  0.0536],
        [-0.0194, -0.4049,  1.0061, -0.2931, -0.6983,  0.3964, -0.3985,  0.2673],
        [ 0.3076, -0.7524, -0.4285, -0.0803,  0.8191, -0.1863, -1.0960, -0.0571],
        [-0.2418,  0.0883,

Parameter containing:
tensor([[ 0.1956,  0.1177,  0.2377,  0.0774,  0.1371, -0.0224, -0.0842,  0.0471],
        [ 0.1173, -0.0301,  0.1837, -0.0882, -0.4480,  0.2131, -0.3647,  0.3360],
        [-0.0155, -0.2929,  0.0274, -0.1356,  0.2290,  0.0608, -0.2514,  0.0338],
        [ 0.1071,  0.0780,  0.0251, -0.0260,  0.1802, -0.1607, -0.1525,  0.1943],
        [ 0.0188,  0.1198,  0.3605, -0.0645,  0.1661, -0.1909, -0.0626,  0.0899],
        [ 0.0902, -0.0992,  0.1850, -0.3214, -0.1925, -0.0123, -0.1987, -0.1029],
        [ 0.0790,  0.2960, -0.2105,  0.1624,  0.1773,  0.1415, -0.0252,  0.2897],
        [ 0.0320, -0.1088,  0.2249, -0.1543,  0.0611,  0.0381, -0.1239,  0.1704]],
       requires_grad=True)
Parameter containing:
tensor([[-0.1069, -0.0991,  0.0075, -0.0558,  0.2214, -0.0337, -0.0164,  0.3142],
        [-0.0933, -0.3012,  0.2969, -0.3467, -0.2461,  0.0060, -0.1909,  0.1856],
        [ 0.4285, -0.0357, -0.0813,  0.1169,  0.2033,  0.0615, -0.6569, -0.0259],
        [-0.1248,  0.2590,

Parameter containing:
tensor([[ 0.0967, -0.0188, -0.0416,  0.0842,  0.1434, -0.0497, -0.1900, -0.0071],
        [-0.1292, -0.0268, -0.0501, -0.0284, -0.2638, -0.0495,  0.1060,  0.0998],
        [ 0.1034,  0.0923, -0.1493,  0.1954,  0.0864, -0.0311, -0.0744,  0.1543],
        [ 0.0686,  0.0177, -0.1877,  0.0004,  0.0053, -0.1573, -0.0227,  0.2849],
        [-0.0246,  0.0435, -0.0522,  0.0844, -0.0545,  0.1698, -0.0011,  0.0787],
        [-0.1196,  0.2014,  0.0022, -0.1372, -0.0964, -0.0022, -0.1371,  0.0003],
        [-0.1513,  0.0596,  0.1435, -0.0551,  0.1938, -0.1089, -0.0654, -0.1025],
        [-0.0099, -0.1150,  0.0945,  0.1469,  0.1651, -0.0817, -0.1882, -0.0222]],
       requires_grad=True)
Parameter containing:
tensor([[ 0.1967,  0.1725,  0.1837,  0.1136, -0.0369,  0.0100,  0.0094,  0.0742],
        [ 0.0485,  0.0337, -0.0797, -0.0624, -0.2586, -0.1301, -0.4315,  0.0567],
        [ 0.0120,  0.0229,  0.1150,  0.0677,  0.2116,  0.1411, -0.1147,  0.1605],
        [-0.0030,  0.0794,

Parameter containing:
tensor([[-0.1756,  0.0922,  0.0958, -0.0862, -0.1300, -0.0458, -0.0578, -0.0973],
        [ 0.0714, -0.1057, -0.1607, -0.0243, -0.0382,  0.1236,  0.0504, -0.0024],
        [-0.0745, -0.1672,  0.0640,  0.3030,  0.1551,  0.1282, -0.1484,  0.0747],
        [ 0.0125,  0.0033,  0.0004,  0.1060,  0.1274, -0.1454,  0.0102,  0.2327],
        [ 0.0823,  0.2317, -0.1689, -0.1535, -0.0549,  0.1174,  0.0162, -0.1736],
        [-0.0755, -0.0875, -0.0972, -0.1952, -0.0086, -0.0945,  0.0691, -0.2606],
        [ 0.2193,  0.2430, -0.0892,  0.0929,  0.0984,  0.0710,  0.0455, -0.1179],
        [-0.0753,  0.1599,  0.0013,  0.1593, -0.0640,  0.1466,  0.1613,  0.0092]],
       requires_grad=True)
Round 6 | Validation Loss: 50.862850189208984
Parameter containing:
tensor([[-0.0287,  0.0649, -0.1579, -0.0004, -0.1149, -0.1112,  0.1312, -0.0968],
        [ 0.1001, -0.0645,  0.1640, -0.0791, -0.0167, -0.1527,  0.0886, -0.2596],
        [-0.0099, -0.1297,  0.0247,  0.0381, -0.0389, -0.0030,

Parameter containing:
tensor([[-0.1032, -0.0017,  0.0123, -0.2006, -0.0156, -0.1862,  0.0023, -0.2118],
        [-0.2725, -0.0450, -0.1199, -0.2080,  0.0208,  0.1227,  0.0505, -0.0275],
        [-0.1603,  0.0806,  0.2156,  0.0004,  0.0543, -0.0786,  0.0770,  0.1733],
        [ 0.0366, -0.3588,  0.1841,  0.1874,  0.0300, -0.0149,  0.0041,  0.1000],
        [-0.1062,  0.0822, -0.1918,  0.0104,  0.0686,  0.0441, -0.3643, -0.2591],
        [-0.1563,  0.0645,  0.0154, -0.0694, -0.0651, -0.0444,  0.0527,  0.1028],
        [ 0.0649, -0.2608, -0.1404, -0.1292, -0.1543,  0.0065, -0.1130, -0.1743],
        [-0.1443,  0.0900,  0.0806,  0.1405, -0.0008, -0.0258,  0.0932, -0.1457]],
       requires_grad=True)
Round 9 | Validation Loss: 53.10731506347656
Parameter containing:
tensor([[-0.0794, -0.0202, -0.2633,  0.0751,  0.0221, -0.0386, -0.1049, -0.1278],
        [ 0.0091, -0.0261, -0.2929,  0.0063,  0.0917, -0.0362,  0.2222,  0.0699],
        [ 0.0872,  0.0394,  0.0912, -0.1068, -0.0342, -0.1352, 

Parameter containing:
tensor([[-0.1078, -0.2177,  0.0313, -0.0388,  0.0952,  0.0307, -0.0147, -0.0634],
        [-0.1158,  0.0658,  0.1168, -0.2164, -0.1082, -0.1144, -0.1995,  0.2938],
        [-0.1019,  0.0304, -0.0074, -0.0186, -0.0832, -0.0920, -0.2071,  0.0937],
        [-0.1249,  0.0095, -0.0613,  0.0809, -0.2046,  0.0678, -0.0807,  0.1351],
        [ 0.1603, -0.0341,  0.2245, -0.1640,  0.1404,  0.0367, -0.1702, -0.0804],
        [-0.0147, -0.0578, -0.0110, -0.1710,  0.1115, -0.0215,  0.0956, -0.1236],
        [-0.1293, -0.1854, -0.0034, -0.2968,  0.0322,  0.1598, -0.0286, -0.1723],
        [-0.0478,  0.0005,  0.1113, -0.0739,  0.1923,  0.0527, -0.0077, -0.0943]],
       requires_grad=True)
Round 12 | Validation Loss: 51.812156677246094
Parameter containing:
tensor([[-0.0452, -0.1046,  0.0378, -0.0343,  0.1071, -0.1098, -0.0087, -0.0695],
        [ 0.1224,  0.0953,  0.2439, -0.0530,  0.0865, -0.0999,  0.0613,  0.0126],
        [ 0.0408,  0.0270,  0.1317, -0.0038, -0.1245, -0.1499

Parameter containing:
tensor([[ 0.1576, -0.1079, -0.0023, -0.0235, -0.1081, -0.1268,  0.1522,  0.1275],
        [-0.0807,  0.1063, -0.0499, -0.0021, -0.1189,  0.0406, -0.0148, -0.0316],
        [ 0.0281,  0.0850,  0.2085, -0.0580, -0.0184,  0.0112,  0.1299, -0.2256],
        [-0.0200,  0.0779, -0.1272, -0.0509,  0.0613, -0.0986,  0.0790, -0.0654],
        [ 0.1944, -0.1118, -0.0444,  0.2473, -0.0353, -0.1354,  0.0085, -0.1329],
        [ 0.0756, -0.1946,  0.0292,  0.1130,  0.0670,  0.1506,  0.0307, -0.1476],
        [-0.1678, -0.0213, -0.1995, -0.1277, -0.0061,  0.0098,  0.1410,  0.1128],
        [ 0.1890,  0.1674,  0.1253, -0.0082, -0.0853,  0.1600, -0.1568,  0.1002]],
       requires_grad=True)
Round 15 | Validation Loss: 52.522281646728516
Parameter containing:
tensor([[ 0.0190, -0.2341, -0.0276,  0.1044,  0.0546,  0.1007,  0.1676, -0.1829],
        [ 0.1335, -0.0632,  0.1344, -0.1125,  0.1231, -0.0028, -0.1352, -0.0974],
        [-0.2452, -0.0441,  0.0495, -0.2185, -0.1413, -0.0875

Parameter containing:
tensor([[ 0.1284,  0.0162,  0.0930, -0.0314, -0.0441, -0.0759,  0.1343,  0.0398],
        [ 0.1207, -0.2209, -0.0198, -0.3061, -0.2300,  0.2551,  0.1070, -0.0975],
        [-0.0251,  0.0352,  0.0422, -0.1122, -0.0193, -0.1629,  0.0656, -0.2047],
        [ 0.0308, -0.0347,  0.0701,  0.0128, -0.0688,  0.0215,  0.2349,  0.0354],
        [ 0.0582, -0.1035, -0.0407,  0.1340,  0.0874,  0.0871,  0.0037, -0.1012],
        [ 0.1361, -0.1162, -0.0415,  0.0044,  0.0723, -0.2242, -0.0289,  0.0669],
        [ 0.1754,  0.2006, -0.0191,  0.0620, -0.1424,  0.2923,  0.0539,  0.0649],
        [-0.0892, -0.1656, -0.0219,  0.0903, -0.1248, -0.0100,  0.0424, -0.1137]],
       requires_grad=True)
Round 18 | Validation Loss: 52.30799865722656
Parameter containing:
tensor([[-0.1174,  0.0696,  0.1618,  0.0055,  0.2066, -0.2664,  0.0111,  0.2258],
        [-0.0540, -0.1069, -0.1137, -0.3686, -0.0321,  0.0888,  0.0524,  0.0227],
        [-0.0725, -0.2187, -0.0038, -0.2122,  0.1628, -0.0256,

(LSR_tensor(
   (factor_matrices): ModuleList(
     (0): ParameterList(
         (0): Parameter containing: [torch.FloatTensor of size 64x8]
         (1): Parameter containing: [torch.FloatTensor of size 64x8]
     )
     (1): ParameterList(
         (0): Parameter containing: [torch.FloatTensor of size 64x8]
         (1): Parameter containing: [torch.FloatTensor of size 64x8]
     )
   )
 ),
 [tensor(84.5066),
  tensor(59.4766),
  tensor(53.5363),
  tensor(51.4649),
  tensor(52.6030),
  tensor(51.8384),
  tensor(50.8629),
  tensor(53.8151),
  tensor(51.5081),
  tensor(53.1073),
  tensor(52.5472),
  tensor(51.2425),
  tensor(51.8122),
  tensor(51.1372),
  tensor(51.7598),
  tensor(52.5223),
  tensor(52.0205),
  tensor(51.7693),
  tensor(52.3080),
  tensor(52.3636)])